### ISSUE TITLE
EPIC: Direct Selection & Retention

### ISSUE THREAD

**Issue by maciej-jaworski** [unicef/un-partner-portal#1143]
# Agency

- [x] Ability to filter list of direct selections & retention by agency, country, status, focal point, sector and areas of specialization and direct selection source.
- [x] Ability to view all direct selection & retentions irrespective of agency
- [x] Ability to view justification reason and summary, including any uploads (if applicable) of a direction selection & retention within one’s agency at any time.
- [x] Ability to restrict viewing justification reason and summary, including any uploads (if applicable) of a direction selection & retention to user’s agency until finalization
- [x] Ability to indicate a CSO, regardless of its verification status, for a direct selection & retention
- [x] Ability to directly select or retain only a single CSO, provided that it has verified status, for partnership before publishing for selection or retention.
- [x] Ability to view information such as project location, project background, expected results about the direct selection
- [x] Ability to optionally upload a single document in the justification summary when creating a direct selection & retention
- [x] Ability to save, edit, delete or publish a direct selection & retention
- [x] Ability for the focal point and creator of a direct selection & retention to be notified when the CSO responds
- [x] Ability to view on the Dashboard and DS/R Overview Page, whether the CSO accepted or declines the direct selection & retention

# Partner

- [x] Ability for the CSO to be notified when a direct selection & retention offer--whether UN-initiated or converted from an UCN submitted by the CSO-- has been made by a participating agency.
- [x] Ability for CSO users to view the details of a direct selection & retention offer made to their organisation
- [x] Ability for CSO to download the direct selection & retention in a presentable PDF format
- [x] Ability for a CSO to accept or decline a partnership offer made via direct selection & retention
- [x] Ability for CSO users to view all direct selection & retention offers made to their organization, including DSR source, i.e. UN-initiated or conversion from UCN.
- [x] Ability to restrict the response to a direct selection offer to the following roles: HQ Partner, Admin/Editor, Country-specific Admin/Editor
- [x] Ability to restrict response to direct selection until the CSO confirms that their profile is up to date.
