### ISSUE TITLE
EPIC: Verification & Observation

### ISSUE THREAD

**Issue by maciej-jaworski** [unicef/un-partner-portal#1156]
# Partner Verification
- [x] Ability to automatically mark a CSO’s profile as “Pending Verification” by default upon entry into the portal.
- [ ] Remove the ability for Agency users to verify Incomplete profiles by greying out the “Add New Verification” button on the CSO Profile.
- [x] Ability to review a CSO’s profile and mark the status of the profile as “Verification: Passed” if the CSO meets the verification requirements and “Verification: Failed” if the CSO does not meet the verification requirements.
- [x] Ability to automatically show if a CSO has an observation or risk flag against its profile, and the content of the observation during verification according to the R&P Matrix.
- [x] Maintain the ability to review details of current and past verifications made to a CSO’s profile.
- [x] Maintain the ability to view the date a CSO was verified, the name and agency of the person who performed the verification.
- [x] Ability to restrict verification to advanced editor and HQ editor roles.
- [x] Ability to restrict the user from verifying a CSO if the profile is incomplete.
- [x] Ability to restrict verification if there is a potential match of the organization’s name or key personnel on the UN Security Council Sanctions List.
- [x] Ability to restrict verification of INGO HQ’s to HQ editor.
- [x] Ability to restrict verifying the CO of INGOs if the HQ profile has status ‘Verification: Pending’ or ‘Verification: Failed’ and/or has a red risk flag.
- [x] Restrict the ability to Verify HQ profile to only the HQ Editor. The option to do so will be removed from the UI if the user is not an HQ Editor.
- [x] In the case that a user without the permissions is blocked, they will need to prompt the HQ Editor to verify outside of the UNPP
- [x] Ability to restrict verifying a CSO with a red risk flag according to the R&P Matrix.
- [x] Ability to restrict viewing comments on a verification to Advanced Editor, HQ editor roles and MFT Users as explained in the R&P Matrix.
- [x] Ability to prompt user to confirm verification prior to changing verification status.

# Partner Observations
- [x] Ability to view potential matches on the UN Security Council Sanctions List and indicate if the organization or individual is ‘Not a true Match’ or a ‘Confirmed Match’.
- [x] On the instance when a partner matches with sanctions list, an observation (Yellow Risk) is generated from the system with the following criteria:
  - The risk observation comment will display what criteria matched (Text String) with the Sanctions List.
  - The risk observation will be categorized as "Sanctions Match".
- [x] Ability to restrict Partners that have a risk observation under the category of "Sanctions Match" from being selected by Agency Users. (i.e: Button will be grayed out).
- [x] Ability to ensure that the name of a CSO is not flagged in subsequent scans if the potential match on the UN Sanctions list was manually determined to be ‘Not a true match’.
- [x] Ability to add an observation to a CSO’s profile at any time.
- [x] Ability to make the user’s email address required for completing an observation.
- [x] Ability to add a category to the selected flag type (e.g.: Fraud and corruption, violation of protection safeguards, sexual exploitation and abuse, sanctions match, support to terrorism, other.)
- [x] Ability to update an observation on a CSO’s profile by invalidating or escalating. Upon updating an observation a new comment field titled "Reason for Decision" will be generated and the content entered there will display in the expanded row details from the observation list view.
- [x] Ability to mark an observation as risk related by appending a yellow risk flag to the CSO’s profile
- [x] Ability to escalate a yellow risk flag to HQ
- [x] Ability to mark a CSO with an escalated risk Red flag for the CSO to be deactivated.
- [x] Ability to defer an escalated risk flag to the CO for resolution, changing the escalated flag back to a Yellow Flag.
- [x] Ability to invalidate an observation and yellow risk flag, but retain the history of the observation or flag, even if it was found to be unsubstantiated or no longer relevant
- [x] Ability to view details of past observations and flags made to a CSO’s profile
- [x] Ability to view the date a CSO received an observation or risk flag, the name, email and agency of the person who gave the observation or risk flag
- [x] Ability to escalate to HQ an organization that is not a legitimate CSO by adding an escalated flag to the profile through the established observations workflow.
- [x] Ability for all the country profiles (i.e. “children”)of an INGO to “inherit” the risk flags appended to its parent’s INGO HQ profile.
- [x] Ability to send notification to the super administrator when a CSO account has been marked for deactivation.
- [x] Ability to restrict adding observations and risk flags to Advanced Editor, HQ editor and MFT users.
- [x] Ability to restrict editing (  invalidating or escalating) an observation or risk flag to the user who created the observation or risk flag
- [x] Ability to restrict marking an account for deactivation (red risk flag) to HQ editor
- [x] Ability to restrict the account deactivation of a CSO with a confirmed match on the UN Sanctions to the super administrator
- [x] Ability to restrict deactivation of a CSO’s account to the super administrator
- [x] Ability to require an agency user when flagging a CSO’s profile to provide the following information: 
  - Comment box for additional details
  - Email of user
  - (optional) Telephone for additional follow-up
  - (optional) Attachment
- [x] Ability to keep a record of CSO’s observations and flags.
- [x] Ability to deactivate an INGO’s HQ and all subsidiary accounts if the HQ profile of an INGO receives a confirmed red flag.
- [x] Ability to restrict viewing the comments on observations and flags to advanced editor, MFT user and HQ editor.

**Comment by maciej-jaworski** [comment]
> Ability to restrict verifying a CSO with a red risk flag according to the R&P Matrix.

Latest permission matrix doesn't seem to include that option.

**Comment by maciej-jaworski** [comment]
>  Ability to add a category to the selected flag type (e.g.: Fraud and corruption, violation of protection safeguards, sexual exploitation and abuse, sanctions match, support to terrorism, other.)

Category list missing

**Comment by maciej-jaworski** [comment]
> Ability to restrict adding observations and risk flags to Advanced Editor, HQ editor and MFT users.
this contradicts permission matrix
