### ISSUE TITLE
EPIC: Reports

### ISSUE THREAD

**Issue by maciej-jaworski** [unicef/un-partner-portal#1232]
Ability to select from a list of reports to run. Reports are the following:    
- [x] Partner Profile
- [x] Partner Mapping 
- [x] CFEI Management
- [x] Verification & Observations
- [x] CSO Contact Information

Ability to select a number of filters to run per report.
- Partner Information:
  - Country
  - Type of Organization
  - Registered
  - UN Experience
  - Country Office
  - Sector & Area of Specialization
- CFEI Management
  - Country
  - Project Location
  - Agency
  - Type of Call
  - Status
  - Type of Location
  - Sector & Area of Specialization
  - Posting Year
- Verification & Observations
  - Country
  - Type of Organization
  - Profile Type
  - Verification Status
  - Verification Year
  - Observations

Requirements:
- [x] Ability to view report results in the portal.
- [x] Ability to export results of report to an Excel document.
- [x] Ability to restrict data in CFEI Management report to agency of the user.
- [ ] Ability to restrict Verifications & Observations report to advanced editor, MFT user and HQ editor.
- [x] Ability to check, via reports, the number of direct selection & retention made per country and by user’s own agency
- [x] Ability to compare, via reports, the number of UN initiated direct selections to CSO initiated direct selections, for user’s own agency
- [x] Ability to generate a report on the verification status of CSOs.

**Comment by maciej-jaworski** [comment]
@brandinalexander Can we get a clarification, what is understood by filtering partner by `Country Office`?

**Comment by maciej-jaworski** [comment]
Report endpoints:
- `/api/reports/projects/`
- `/api/reports/partners/`
- `/api/reports/verifications-observations/`
