### ISSUE TITLE
EPIC: Pilot Enhancements

### ISSUE THREAD

**Issue by maciej-jaworski** [unicef/un-partner-portal#1270]
FYI: Checking task as done means it's either completed OR a child issue has been created.

https://docs.google.com/spreadsheets/d/1NT1OF70XY7RxuBfLebGogG2TDsUmr4ijnl4ylDWjEt4/edit#gid=1788662432

# CFEI General
- [x] Like the DSR process, a user should have the ability to save a draft CFEI
- [x] A CSO and UN user should have the ability to download a well formatted PDF copy of the CFEI
- [x] A basic editor cannot directly publish a CFEI, and must instead send a draft CFEI to the focal point to publish
- [x] New CFEI uploads: #1275
  - Permissions: Basic and advanced editor, PAM user
  - When creating a CFEI, user has the option to upload up to five attachments, giving a description of the attachments
- [x] CFEI table #1273 
  - should also include the CFEI ID and focal point
  - new filters on the agency side - CFEI ID, CFEI focal point
- [x] An advanced editor and PAM user can directly publish a CFEI
- [x] Once the CN has been submitted by a user with the correct permissions, the partner reader can download (but not delete) the submitted document. #1274

# Dashboard
- [ ] The CFEIs should not disappear once the user has opened the CFEI. The user can have a view of all CFEIs they assessed

# CFEI Assessment
- [x] Preselected List tab: If only one reviewer is selected on a CFEI, the user can optionally indicate that they are uploading the scores on behalf of a committee (i.e. entering one set of scores that represents the consensus of a multi-member offline committee). CFEI review update #1276 
- [x] In the application list tab, display verification badge next to the name of the organization
- [x] Preselected List tab: Remove Review progress column from pre-select page
- [x] Preselected List tab: Remove the “Select” button from the CSO application page
- [x] Preselected List tab: Change the name section labelled “comments” in the CSO application page to “Feedback to partner”
- [x] Preselected List tab: Once the recommend button is selected, the user is directed to the Results tab where they will be required to fill in the results summary
- [x]  The advanced editor/MFT user will receive a notification when the recommendation has been sent to them
- [x] Preselected List tab: In the CFEI creator or focal point view of the pre-select list, when the user hovers over the average score column, it should show the breakdown of the average score per reviewer #1282
- [x] Preselected List tab:  Remove the ability for the CFEI creator or focal point to add a review on behalf of a reviewer
- [x] Preselected List tab: When the CFEI creator or focal point selects a CSO’s application, in the Reviews section, it should show the date the assessment was completed. This date completed is derived from the date the reviewer selected “complete assessment”
- [x] Preselected List tab: Remove the ability to send the feedback from the application page. Comments are sent to the CSO when the CFEI is finalized
- [x] Preselected List tab: The CFEI creator or focal point can ‘recommend’ one or more CSOs for a CFEI
- [x] Preselected List tab: Once a CFEI has been sent to the advanced editor or MFT user for selection, the CFEI creator or focal point can no longer add a reviewer to the CFEI
- [x] Once all the required sections are complete, the “send” button is enabled for basic editors or PAM users. If the creator is an advanced editor, the user will have the “select” button enabled
- [x] When a recommended partner is sent to the advanced editor/MFT user, the user can no longer make edits to the review summary or change the recommendation
- [x] The advanced editor/MFT user, from the results tab, can either “Select” the recommended partner(s) or go to the pre-selected tab, recommend another CSO and then select them.
- [x] The date the partner was ‘selected’ and selected by should be captured in the recommended partner section.
- [x] DECLINE SELECTION - If a CSO declines selection on a CFEI, once the UN user is notified of this declination, the CFEI creator or focal point can recommend and select another partner from the pre-select list. The user however, cannot select again the CSO that declined selection.
- [x] Preselected List tab: Add a “Complete Assessment” button on the preselected list tab. Once a reviewer has completed the assessment of all applications, the user clicks the tab to indicate the review process is complete.
- [x] Preselected List tab:When the user clicks the “complete assessment button” a confirmation modal is displayed stating: “Are you sure you want to complete your assessments? Once your assessments are completed you will no longer be able to edit your scores”
- [x]  Preselected List tab: Restrictions:
  - Once a reviewer has selected the “complete assessment” button they cannot edit their scores. From this point forward, they only have view permissions on their scores
  - Only CFEI creator or focal point can input comments in the “Feedback to partner” section
  - A user cannot recommend a CSO until all reviewers have completed their assessments i.e. clicked the “complete assessment” button
  - A CSO can only be recommended from the pre-select page
- [ ] Once a CFEI has been finalized the following should occur:
  - All reviewers on the CFEI should be able to view their score and all the information in the results tab.
  - The CFEI focal point and creator should be able to view all reviewers’ scores and all the information in the results tab
  - All advanced editors and MFT users should be able to view the CFEI overview tab and all the information on the results tab for their own UN agency
  - All basic editors and readers can view the CFEI overview tab and the name of the selected partner in the results tab. A UNICEF user, for example, has the same view rights as a reader on a finalized UNHCR CFEI
- [x] Preselected List tab: Add new column in the CFEI creator or focal point view titled “Recommend Partner”. In each row, add a “recommend” button, where the creator or the focal point can nominate the best CSO/concept note. This recommend button is disabled until all reviewers have selected the “complete assessment” button
- [x] Once the send button is selected, a modal is displayed requiring the user to confirm that they want to send the recommended CSOs to the advanced editor/MFT user, informing them that the advanced editor/MFT user will receive a notification of the recommendation.
- [x] Once a partner is “Selected” there will be a modal where the advanced editor/MFT user will give a justification for selection (required).
- [x] Results tab: The results tab will have the following sections:• 
  - Review summary: The results summary is now required to be filled before the user can ‘send’ the recommended partner(s) to the advanced editor or MFT user for ‘Selection’
  - Recommended Partner(s): This is the present “Selected Partners” section. It is a subset of the pre-select list that were recommended. Expanding this section displays the criteria for assessment and the average score the CSO received for each criteria and the total average score. It also contains the notes from each reviewer.
  - The user can withdraw a recommendation from this section.
  - Preselected Partners: This is a new section that contains the subset of CSOs from the pre-selected lists who were not recommended. Like the Recommended partners section, when expanded it displays the criteria, average score per criteria, total average and reviewer(s) notes
- [x] Add another date field titled “Clarification Request Deadline”
  - A notification email will be sent to the UN user informing them that the clarification for requests deadline has passed and that they can respond to the queries.
  - The UN user can view, and download in a well formatted PDF document the clarification requests submitted by CSOs on the CFEI
  - Once the deadline for clarification requests has passed, the UN user can upload up to three documents, with the ability to name each document with responses to all questions and any additional information deemed necessary
  - Restriction: UN user cannot upload responses prior to the clarification request deadline. The upload button is disabled until this date has passed
  - Permissions
  - Advanced editor, Basic editor, MFT User, PAM user can view the queries received from CSOs if they are the creator or focal point of the CFEI
  - Advanced editor, Basic editor, MFT User, PAM user can download a PDF of the queries received from CSOs if they are the creator or focal point of the CFEI
  - Advanced editor, Basic editor user can upload a document with the responses to queries if they are the creator or focal point of the CFEI.  PAM user can upload a document with the responses to queries if they are the creator of the CFEI
  - All users—on both the UN and CSO side—can view the responses to the clarification queries on the CFEI
  - CSOs - On the CFEI overview page, a section titled “Request for clarification”. 
  - The CSO user can click on the 3 dots and submit to the UN a request for clarification
  - Adding requests is enabled from date of CFEI publication to the “Clarification Request Deadline” date indicated in the CFEI. Once the date has passed, the user can no longer submit requests.
  - Any CSO that has applied to a CFEI must be able to continuously view that CFEI and any clarification questions it submitted regarding that CFEI. In contrast, a CSO that did not apply to a CFEI will not be able to view the CFEI after the application deadline has passed and will also not be able to view any clarification questions it submitted.
  - After the Clarification Request Deadline has passed, the CSO can, in the CFEI overview page, download a PDF copy of the UN agency’s consolidated response to clarification questions
  - Permissions: Partner HQ administrators, Partner HQ editors, administrators and editors can add clarification requests.
  - All CSO users can view clarification requests submitted by their organization.
  - All CSO users can view the consolidated UN response to clarification requests.
